import React from 'react';
import { ShieldAlert, Cpu } from 'lucide-react';
import { RiskAssessment } from '../../types';
import { Badge } from '../common/Badge';

interface RiskIndicatorProps {
  assessment: RiskAssessment;
}

export const RiskIndicator: React.FC<RiskIndicatorProps> = ({ assessment }) => {
  const scorePercent = (assessment.overallScore / assessment.maxScore) * 100;

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-rose-500 stroke-rose-500 bg-rose-500';
    if (score >= 50) return 'text-amber-500 stroke-amber-500 bg-amber-500';
    return 'text-emerald-500 stroke-emerald-500 bg-emerald-500';
  };

  return (
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm space-y-6 transition-colors font-sans">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-200 dark:border-slate-800 pb-4">
        <div className="flex items-center space-x-2">
          <ShieldAlert className="w-5 h-5 text-rose-600 dark:text-rose-400" />
          <h3 className="font-headline text-lg font-bold text-slate-900 dark:text-slate-100">
            Risk Assessment
          </h3>
        </div>
        <div className="flex items-center space-x-1.5 text-xs text-blue-700 dark:text-blue-400 bg-blue-50 dark:bg-blue-950/60 px-3 py-1 rounded-full border border-blue-200 dark:border-blue-800/60 font-sans">
          <Cpu className="w-3.5 h-3.5" />
          <span>Generated by the Risk Intelligence Engine</span>
        </div>
      </div>

      {/* Main Score Circular Display Box */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6 items-center bg-slate-50 dark:bg-slate-950/60 p-5 rounded-xl border border-slate-200 dark:border-slate-800">
        {/* Score Circle */}
        <div className="flex flex-col items-center justify-center space-y-1">
          <div className="relative w-28 h-28 flex items-center justify-center">
            <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
              <path
                className="text-slate-200 dark:text-slate-800 stroke-current"
                strokeWidth="3.5"
                fill="none"
                d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
              />
              <path
                className={`transition-all duration-700 ease-out ${getScoreColor(assessment.overallScore)}`}
                strokeDasharray={`${scorePercent}, 100`}
                strokeWidth="3.5"
                strokeLinecap="round"
                fill="none"
                d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
              />
            </svg>
            <div className="absolute flex flex-col items-center justify-center">
              <span className="font-headline text-3xl font-extrabold text-slate-900 dark:text-slate-100 tracking-tight">
                {assessment.overallScore}
              </span>
              <span className="text-[10px] font-mono text-slate-500 dark:text-slate-400">/ 100</span>
            </div>
          </div>
        </div>

        {/* Priority Status Box */}
        <div className="sm:col-span-2 space-y-2.5 text-left">
          <div className="flex items-center space-x-2">
            <Badge variant="high" size="md">
              HIGH PRIORITY
            </Badge>
          </div>

          <p className="text-sm font-semibold text-slate-800 dark:text-slate-200 leading-snug font-sans">
            This case has multiple indicators requiring investigator review.
          </p>
          <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-sans">
            Score evaluated automatically across drug activity telemetry, cross-platform identity linkage, and crypto wallet dispersal trails.
          </p>
        </div>
      </div>

      {/* Factor Breakdown List with Progress Bars */}
      <div className="space-y-4">
        <h4 className="text-xs font-mono font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider">
          Why This Case Is High Risk
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {assessment.factors.map((factor, idx) => (
            <div
              key={idx}
              className="p-3.5 bg-slate-50 dark:bg-slate-950/60 rounded-lg border border-slate-200 dark:border-slate-800 space-y-2"
            >
              <div className="flex items-center justify-between space-x-2">
                <span className="text-xs font-semibold text-slate-800 dark:text-slate-200 font-sans">{factor.category}</span>
                <span className="text-xs font-mono font-bold text-rose-600 dark:text-rose-400 bg-rose-50 dark:bg-rose-950/60 px-2 py-0.5 rounded border border-rose-200 dark:border-rose-800/60">
                  +{factor.points} pts
                </span>
              </div>
              {/* Progress bar matching template style */}
              <div className="w-full bg-slate-200 dark:bg-slate-900 h-1.5 rounded-full overflow-hidden border border-slate-300 dark:border-slate-800/60">
                <div
                  className="bg-rose-500 h-full rounded-full"
                  style={{ width: `${Math.min(100, (factor.points / 30) * 100)}%` }}
                />
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
