import React from 'react';
import { ShieldAlert, Cpu, AlertTriangle } from 'lucide-react';
import { RiskAssessment } from '../../types';
import { Badge } from '../common/Badge';

interface RiskIndicatorProps {
  assessment: RiskAssessment;
}

export const RiskIndicator: React.FC<RiskIndicatorProps> = ({ assessment }) => {
  const scorePercent = (assessment.overallScore / assessment.maxScore) * 100;

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-rose-500 stroke-rose-500 bg-rose-500';
    if (score >= 50) return 'text-amber-500 stroke-amber-500 bg-amber-500';
    return 'text-emerald-500 stroke-emerald-500 bg-emerald-500';
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 shadow-xl space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-3">
        <div className="flex items-center space-x-2">
          <ShieldAlert className="w-5 h-5 text-rose-400" />
          <h3 className="font-mono font-bold text-sm text-slate-100 uppercase tracking-wider">
            Risk & Threat Intelligence Display
          </h3>
        </div>
        <div className="flex items-center space-x-1.5 text-[11px] font-mono text-cyan-400 bg-cyan-950/40 px-2.5 py-1 rounded border border-cyan-500/30">
          <Cpu className="w-3.5 h-3.5 animate-pulse" />
          <span>Member 4 Risk Engine</span>
        </div>
      </div>

      {/* Visual Risk Gauge & Main Score */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center bg-slate-950/80 p-4 rounded-xl border border-slate-800">
        {/* Circle Gauge */}
        <div className="flex flex-col items-center justify-center space-y-1">
          <div className="relative w-28 h-28 flex items-center justify-center">
            <svg className="w-full h-full transform -rotate-90" viewBox="0 0 36 36">
              <path
                className="text-slate-800 stroke-current"
                strokeWidth="3.5"
                fill="none"
                d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
              />
              <path
                className={`transition-all duration-1000 ease-out ${getScoreColor(assessment.overallScore)}`}
                strokeDasharray={`${scorePercent}, 100`}
                strokeWidth="3.5"
                strokeLinecap="round"
                fill="none"
                d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
              />
            </svg>
            <div className="absolute flex flex-col items-center justify-center">
              <span className="text-3xl font-extrabold font-mono text-slate-100 tracking-tighter">
                {assessment.overallScore}
              </span>
              <span className="text-[10px] font-mono text-slate-400">/ 100</span>
            </div>
          </div>
          <p className="text-[10px] font-mono text-slate-400">Backend Threat Score</p>
        </div>

        {/* Priority Status Box */}
        <div className="md:col-span-2 space-y-2 text-left">
          <div className="flex items-center space-x-2">
            <Badge variant={assessment.riskLevel === 'HIGH' ? 'high' : 'medium'} size="md">
              {assessment.riskLevel} PRIORITY TARGET
            </Badge>
            <span className="text-xs text-slate-400 font-mono">Case: {assessment.caseId}</span>
          </div>

          <p className="text-xs text-slate-300 leading-relaxed">
            The threat score was generated by the backend AI risk engine based on cross-correlated intelligence signals, darknet listings, on-chain crypto flow, and topological graph centrality.
          </p>

          <div className="flex items-center space-x-2 text-[11px] font-mono text-rose-400/90 pt-1">
            <AlertTriangle className="w-3.5 h-3.5 shrink-0" />
            <span>Requires immediate investigator review & multi-jurisdiction interdiction.</span>
          </div>
        </div>
      </div>

      {/* Explainable AI Risk Breakdown Factors */}
      <div className="space-y-3">
        <h4 className="text-xs font-mono font-semibold text-slate-400 uppercase tracking-wider flex items-center justify-between">
          <span>Threat Factor Decomposition</span>
          <span className="text-[10px] font-normal text-slate-500">Provided by Backend Risk API</span>
        </h4>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
          {assessment.factors.map((factor, idx) => (
            <div
              key={idx}
              className="p-3 bg-slate-950/60 rounded-lg border border-slate-800/90 flex flex-col justify-between space-y-1 hover:border-slate-700 transition-colors"
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-slate-200">{factor.category}</span>
                <span className="text-xs font-mono font-bold text-rose-400 bg-rose-950/40 px-2 py-0.5 rounded border border-rose-500/30">
                  +{factor.points} pts
                </span>
              </div>
              <p className="text-[11px] text-slate-400 leading-tight">{factor.description}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
